/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perdig;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class Datapeminjam extends javax.swing.JFrame {

    /**
     * Creates new form Datapeminjam
     */
    public Datapeminjam() {
        initComponents();
        int Harga,total,bayar;
        String jumlah;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        nim = new javax.swing.JTextField();
        jurusan = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_pnjm = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        Tpinjam = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        harga = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jml_buku = new javax.swing.JTextField();
        baru = new javax.swing.JRadioButton();
        bekas = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(610, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("DATA PEMINJAM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Nama:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("NIM:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Jurusan:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Alamat:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Tanggal Peminjaman:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 200, -1));
        getContentPane().add(nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 200, -1));
        getContentPane().add(jurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 200, -1));
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 200, -1));

        tbl_pnjm.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tbl_pnjm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "NIM", "Jurusan", "Alamat", "Tpinjam", "Jml buku"
            }
        ));
        jScrollPane2.setViewportView(tbl_pnjm);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 540, 150));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 70, -1));

        Clear.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 70, -1));

        exit.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 70, -1));
        getContentPane().add(Tpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 70, -1));

        back.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 70, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Jenis Buku:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        harga.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        harga.setText("Harga");
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 70, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("Jumlah Buku:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 70, -1));
        getContentPane().add(jml_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 70, -1));

        baru.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        baru.setText("Baru");
        getContentPane().add(baru, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 240, 60, -1));

        bekas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bekas.setText("Bekas");
        getContentPane().add(bekas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 70, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\library-2.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -50, 670, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
nama.getText();
nim.getText();
jurusan.getText();
alamat.getText();
Tpinjam.getText();
jml_buku.getText();
DefaultTableModel model= (DefaultTableModel) tbl_pnjm.getModel();

model.addRow(new Object[]{nama.getText(),nim.getText(),jurusan.getText(),alamat.getText(),Tpinjam.getText(),jml_buku.getText()});        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
nama.setText("");
nim.setText("");
jurusan.setText("");
alamat.setText("");
Tpinjam.setText("");   
jml_buku.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_ClearActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
if (JOptionPane.showConfirmDialog(null, "Anda yakin ingin keluar?","Warning!!", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
JOptionPane.showMessageDialog(null, "Terimakasih sudah menggunakan Perpustakaan Digital ini");
System.exit(0);    
}
    }//GEN-LAST:event_exitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
new Databuku().setVisible(true);
dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
if (baru.isSelected()){
    String jumlah = jml_buku.getText();
    int bayar = Integer.parseInt(jumlah);
    int Harga = bayar*4500;
    int total = Harga;  
    JOptionPane.showMessageDialog(this,"Total harga yang akan anda bayar: \n"+total);
}else if(bekas.isSelected()){
        String jumlah = jml_buku.getText();
        int bayar = Integer.parseInt(jumlah);
        int Harga = bayar*3500;
        int total = Harga;
        JOptionPane.showMessageDialog(this,"Total harga yang akan anda bayar: \n"+total);
}
JOptionPane.showMessageDialog(this,"Harap dikembalikan 3 hari setelah buku ini dipinjam!!!");
// TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datapeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datapeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datapeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datapeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Datapeminjam utm=new Datapeminjam();
                utm.pack();
                utm.setLocationRelativeTo(null);
                utm.setSize(600, 510);
                utm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JTextField Tpinjam;
    private javax.swing.JTextField alamat;
    private javax.swing.JButton back;
    private javax.swing.JRadioButton baru;
    private javax.swing.JRadioButton bekas;
    private javax.swing.JButton exit;
    private javax.swing.JButton harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jml_buku;
    private javax.swing.JTextField jurusan;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nim;
    private javax.swing.JTable tbl_pnjm;
    // End of variables declaration//GEN-END:variables
}
